@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ1c2VyIiwiaWF0IjoxNzA5MDQwMDc0fQ.LGtWuhEghlfZr2VmK5d2OgBqCHTVRCyU3YXn_5Nckmg
###
GET http://localhost:4000/pythonservices
Authorization: Bearer {{token}}

###
GET http://localhost:4002

###
GET http://localhost:4001

### 
GET http://localhost:4000/cars
Authorization: Bearer {{token}}

###
POST http://localhost:4000/cars
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "marque": "Toyota",
  "modele": "Corolla",
  "year": 2017,
  "color": "white"
}

###
POST http://localhost:4000/auth/register
Content-Type: application/json

{
  "email": "user",
  "password": "password"
}

###
POST http://localhost:4000/auth/login
Content-Type: application/json

{
  "email": "user",
  "password": "password"
}

###
POST http://localhost:4000/auth/logout
Content-Type: application/json
Authorization: Bearer {{token}}
